CREATE TABLE MEMBER 
(
  NAME VARCHAR2(10 BYTE) 
, ID VARCHAR2(10 BYTE) NOT NULL 
, PASSWD VARCHAR2(10 BYTE) 
) 

CREATE TABLE ARTICLE 
(
  TITLE VARCHAR2(20 BYTE) NOT NULL 
, CONTENTS VARCHAR2(100 BYTE) 
, AR_DATE DATE 
, AR_NUM NUMBER(*, 0) 
) 

CREATE TABLE REPLY 
(
  CONTENTS VARCHAR2(100 BYTE) NOT NULL 
, COMM_DATE DATE 
) 